[package]
name = "kitlang"
version = "0.1.1"
edition = "2024"
authors = ["zephhhhhh"]
license = "MIT"
description = "A statically-typed, Rust-inspired programming language designed for embedding"
repository = "https://github.com/zephhhhhh/kitlang"
keywords = ["compiler", "interpreter", "language", "embedded", "scripting"]
categories = ["compilers", "scripting", "addon-support"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
webasm = ["serde", "dep:wasm-bindgen", "dep:js-sys", "dep:web-time"]
serde = ["dep:serde", "dep:serde_json"]

[dependencies]
unicode-xid = "0.2.6"
thiserror = "2.0.17"
slotmap = "1.0.7"
paste = "1.0.15"
humanize-duration = "0.0.7"

wasm-bindgen = { version = "0.2", optional = true }
js-sys = { version = "0.3.83", optional = true }
serde = { version = "1.0.228", features = ["derive"], optional = true}
serde_json = { version = "1.0.145", optional = true }
web-time = { version = "1.1.0", optional = true }